Add renameat2
ygrek/extunix pull request #49
Opened 2023-07-09 07:46 UTC by cyberhuman

- add renameat2 function and flags

- suffix constructors marked with `[@have <feature>]` with `__Not_available` if  <feature> is not available.

- register `ExtUnix.Not_available` with C runtime so it's possible to raise `Not_available` from bindings

2024-08-10 15:26 UTC, MisterDA commented on src/rename.c
> +  caml_leave_blocking_section();
This is incorrect, it is not allowed to use `X_val` macros inside a blocking section.

2024-12-01 02:58 UTC, ygrek requested changes
sorry, didn't see this on time
nice idea with not available constructors

2024-12-01 02:58 UTC, ygrek commented on discover/discover.ml
> +      DEFINE "_GNU_SOURCE";
technically not needed, _GNU_SOURCE is defined for all, see config_defines

2024-12-01 02:58 UTC, ygrek commented on src/rename.c
> +  int ret = renameat2(oldfd, oldname, newfd, newname, flags);
this is not safe, oldname and newname still refer to ocaml heap, need to strdup (or remove blocking section)

2024-12-03 22:13 UTC, ygrek commented
closed in favor of #57

2024-12-03 22:13 UTC, closed without merging